### ISSUE TITLE
[Question] How to keep up to date the list of icons?

### ISSUE THREAD

**Issue by bambinoua** [FaFre/flutter_material_design_icons#1]
The current version of icons is `7.3.67`. Is it possible to update this storage? Or please create an instuction how to do that yourselff.

**Comment by FaFre** [comment]
Thank you for letting me know, I will update the package in few hours with the most recent version

**Comment by FaFre** [comment]
Alright, @bambinoua the updated version has just been released. Please update your dependencies.

**Comment by bambinoua** [comment]
@FaFre thank you for a quick response. Is it possible to update icons using package utility?

**Comment by FaFre** [comment]
Can you explain in more detail please?

**Comment by bambinoua** [comment]
How to update the list of icons on one's own w/o asking you each time when new version is released but you didn't update package?

**Comment by FaFre** [comment]
You can just open an issue here, its also in my interest to keep the package up to date. The generation is a bit complicated for now and requires additional steps. i will work on making this easier in the following releases.
